let ten = prompt("Tên người nhận: ");
let address = prompt("Địa điểm:  ");
let time = prompt("Thời gian: ");
document.write( ten + " thương nhớ,");
document.write("<BR>");
document.write("<BR>");
document.write("Em không biết phải nói sao để anh hiểu rằng, em nhớ anh thật nhiều. Em yêu anh đến khi trái tim này");
document.write("<BR>");
document.write(" tan thành nghìn mảnh. Tất cả những gì em yêu thương, em khát khao và cần đến, chính là anh, mãi mãi");
document.write("<BR>");
document.write(" về sau. Em chỉ muốn ở bên anh, và anh yêu hỡi, em sẽ trở thành người phụ nữ như anh mong muốn.");
document.write("<BR>");
document.write("<BR>");
document.write("Có phải em thật tệ hại, khi cứ nghĩ đến anh thật nhiều, thật lâu và nhất là mỗi khi đêm xuống? Em hứa");
document.write("<BR>");
document.write("sẽ sẽ cố gắng triệu triệu lần hơn thế. Nhưng hơn tất cả, em chỉ mong một ngày nào đó, anh sẽ tự hào");
document.write("<BR>");
document.write("về em, như tự hào về vợ của anh, và mẹ của các con anh (ít nhất là 2 nhé, em vừa mới quyết định đấy!).");
document.write("<BR>");
document.write("Em nhớ thật nhiều cảm giác mỗi đêm anh ôm em và ru em ngủ trong vòng tay. Đêm nay, em chỉ muốn");
document.write("<BR>");
document.write("được gần bên anh… và anh biết không, trái tim em đang đau đớn đến nhường nào.");
document.write("<BR>");
document.write("<BR>");
document.write("Anh yêu thương, đừng bao giờ rời xa em nữa nhé. Yêu anh rất nhiều.")
document.write("<BR>");
document.write("<BR>");
document.write(address + " , " + time);
